version: '3.8'
services:
  db:
    image: postgis/postgis
    container_name: geocode-db
    restart: always
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
      POSTGRES_DB: geocode
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cities500.txt:/docker-entrypoint-initdb.d/cities500.txt

volumes:
  pgdata:
