services:
  db:
    image: postgis/postgis
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - geocode-internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      GEONAMES_URL: ${GEONAMES_URL}
    networks:
      - traefik
      - geocode-internal

networks:
  traefik:
    external: true
  geocode-internal:
    internal: true

volumes:
  pgdata:
