services:
  db:
    image: postgis/postgis
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
      POSTGRES_DB: geocode
    networks:
      - geocode-internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://geo:geo@db:5432/geocode
    networks:
      - traefik
      - geocode-internal

networks:
  traefik:
    external: true
  geocode-internal:
    internal: true

volumes:
  pgdata:
